apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-03-31T04:50:11Z"
  generation: 5
  labels:
    app: aggregator-service
  name: aggregator-service
  namespace: default
  resourceVersion: "206588"
  selfLink: /apis/apps/v1/namespaces/default/deployments/aggregator-service
  uid: 1a4d11b1-730b-11ea-a9c0-42010a800099
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aggregator-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aggregator-service
    spec:
      containers:
      - env:
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: user.service.url
              name: properties-config-map
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: order.service.url
              name: properties-config-map
        image: veerpalkaur/ecommerce-gke-app:aggregator-service
        imagePullPolicy: IfNotPresent
        name: ecommerce-gke-app-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-31T04:50:11Z"
    lastUpdateTime: "2020-03-31T06:03:07Z"
    message: ReplicaSet "aggregator-service-5c7c466c88" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-31T06:03:09Z"
    lastUpdateTime: "2020-03-31T06:03:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
