apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-12T09:13:21Z"
  generation: 10
  labels:
    app: aggregator-service
  name: aggregator-service
  namespace: default
  resourceVersion: "329540"
  selfLink: /apis/apps/v1/namespaces/default/deployments/aggregator-service
  uid: dadef7cf-7c9d-11ea-a8bf-42010a800230
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aggregator-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aggregator-service
    spec:
      containers:
      - env:
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: USER_SERVICE_URL
              name: aggregator-config-map
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: ORDER_SERVICE_URL
              name: aggregator-config-map
        - name: OPENTRACING_JAEGER_UDP_SENDER_HOST
          valueFrom:
            configMapKeyRef:
              key: OPENTRACING_JAEGER_UDP_SENDER_HOST
              name: aggregator-config-map
        image: veerpalkaur/ecommerce-gke-app:nagp-aggregator-service
        imagePullPolicy: IfNotPresent
        name: ecommerce-gke-app-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-12T09:13:21Z"
    lastUpdateTime: "2020-04-12T09:13:24Z"
    message: ReplicaSet "aggregator-service-7c8fc98798" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-12T09:33:18Z"
    lastUpdateTime: "2020-04-12T09:33:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1