apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-service-deployment
    labels:
     app: order-service
spec:
    replicas: 3
    selector:
      matchLabels:
        app: order-service
    template:
      metadata:
        labels:
          app: order-service
      spec:  
        containers:
        - name: order-service-container
          image: veerpalkaur/ecommerce-gke-app:order-service
          ports:
          - containerPort: 9091