apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-service-deployment
    labels:
     app: order-service
spec:
    replicas: 3
    selector:
      matchLabels:
        app: order-service
    template:
      metadata:
        labels:
          app: order-service
      spec:  
        containers:
        - name: order-service-container
          image: veerpalkaur/ecommerce-gke-app:nagp-order-service
          ports:
            - containerPort: 9091
          env:
           - name: OPENTRACING_JAEGER_UDP_SENDER_HOST
             valueFrom:
               configMapKeyRef:
                 name: order-service-config-map
                 key: OPENTRACING_JAEGER_UDP_SENDER_HOST
          
