apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
     app: mysql-service
spec:
    containers:
      -  image: mysql:8
         name: mysql
         args:
           - "--default-authentication-plugin=mysql_native_password"
         env:
           - name: MYSQL_ROOT_PASSWORD
             value: password
         ports:
           - containerPort: 3306
             name: mysql
         volumeMounts:
           - name: mysql-persistent-storage
             mountPath: /var/lib/mysql
    volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim