apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service-deployment
    labels:
     app: user-service
spec:
    replicas: 3
    selector:
      matchLabels:
        app: user-service
    template:
      metadata:
        labels:
          app: user-service
      spec:  
        containers:
        - name: user-service-container
          image: veerpalkaur/ecommerce-gke-app:user-service
          ports:
          - containerPort: 9090